name: Build Java application

on:
    workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
              working-directory: java-app
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '21'
        - name: build with maven
          run: mvn clean install
        - uses: actions/upload-artifact@v4
          with:
            name: java-sample
            path: java-app/target/*.jar
        - run: mvn --batch-mode deploy
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
