name: Build Java application

on:
    workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
              working-directory: java-app
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '21'
        - name: build with maven
          run: mvn package
        - uses: actions/upload-artifact@v4
          with:
            name: java-sample
            package: target
