name: Conditional context

on: 
    push:
        branches:
        - main
        - 'feat/**'
    pull_request:
    workflow_dispatch:

jobs:
    conditional-job:
        runs-on: ubuntu-latest
        steps:
            - name: runs when pushed to feature branch
              if: ${{ startsWith(github.ref, 'refs/heads/feat/') }}
              run: echo "Pushed to feature branch: ${{ github.ref_name }}"
            - name: runs when pushed to main
              run: echo "Pushed to main branch"
            - name: runs when workflow is triggered
              if: ${{ github.event_name == 'workflow_dispatch' }}
              run: echo "Workflow triggered"
            - name: runs when pull request is opened
              if: ${{ github.event_name == 'pull_request' }}
              run: echo "Pull request opened"
            - name: echo event origin
              run: echo "Event origin: ${{ github.event_origin }}"
